apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp-getip
  labels:
    app: backend-restapp-getip
    tier: backend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-restapp-getip
  template:
    metadata:
      labels:
        app: backend-restapp-getip
        tier: backend 
    spec: 
      containers:
        - name: backend-restapp-getip
          image: sutirthabagchi21/helloworld:v4-release
          ports:
            - containerPort: 8080      