apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp-getip
  labels:
    app: backend-restapp-getip
    tier: backend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-restapp-getip
  template:
    metadata:
      labels:
        app: backend-restapp-getip
        tier: backend 
    spec: 
      containers:
        - name: backend-restapp-getip
          image: sutirthabagchi21/helloworld:v2-release
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-restapp-getip-service ## VERY VERY IMPORTANT - NGINX PROXYPASS needs this name
spec:
  #type: ClusterIP is a default service in k8s
  selector:
    app: backend-restapp-getip
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-restapp-getip-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: my-backend-service
            port:
              number: 8080
        pathType: Exact